# Generated by Django 5.2.8 on 2025-11-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revendedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fotoDocumento', models.ImageField(blank=True, null=True, upload_to='revendedoras/docs/')),
                ('fotoPerfil', models.ImageField(blank=True, null=True, upload_to='revendedoras/perfis/')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('pendente', 'Pendente')], default='pendente', max_length=10)),
            ],
        ),
    ]
